### ISSUE TITLE
Code still requires an old version of spglib

### ISSUE THREAD

**Issue by nmounet** [aiidateam/aiida_core#430] opened 2017-03-10 17:51 UTC
setup_requirements contains 'pyspglib (for 'atomic_tools') which is the old pip packaged (spglib 1.8.3), that will never be upgraded.
The newest spglib would be installed instead by putting there 'spglib' (current version is 1.9.9).
This involves modifying the StructureData class, possibly also tests and the tcod exporter.

Another weird thing is that it seems both pyspglib and spglib are actually installed in the virtual environment (both are in ~/aiidapy/local/lib/python2.7/site-packages) - even if only pyspglib is present in setup_requirements.

**Comment by giovannipizzi** [comment] 2017-03-10 17:55
Duplicate of #290

**Comment by giovannipizzi** [comment] 2017-03-10 17:56
I think both are installed because spglib is installed by e.g. pymatgen. 
It's something I planned to do, but I don't think we've time before 0.8.

**Comment by giovannipizzi** [comment] 2017-05-11 15:47
Closing as it is a duplicate

**Closed by giovannipizzi** 2017-05-11 15:47 UTC
Labels: topic/PipInstall, type/duplicate, type/enhancement
