### ISSUE TITLE
python3 / pip3 installation fails

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida_core#753] opened 2017-10-10 12:21 UTC
```
$ pip3 install aiida 
...
Collecting aiida-core==0.9.1 (from aiida)
  Downloading aiida-core-0.9.1.tar.gz (24.9MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ewf5qzrt/aiida-core/setup.py", line 13, in <module>
        from setup_requirements import install_requires, extras_require
    ImportError: No module named 'setup_requirements'
    fastentrypoints
```

**Comment by dev-zero** [comment] 2017-10-17 09:59
This is actually not a Python 3 problem, but a packaging issue: `setup_requirements.py` is missing from the `aiida-core-0.9.1.tar.gz` uploaded at pypi and the package is therefore inconsistent. The reason it works with Python 2 is that there is a py2-wheels package which seems to be complete/consistent.

**Comment by dev-zero** [comment] 2017-10-17 10:36
Ok, I can reproduce it when taking the tarball from the 0.9.1 tag and running `python setup.py sdist`. The resulting tarball is missing the `setup_requirements.py`.
I can not reproduce it when doing the same in the "devel" or "release_v.0.10.0" branch, although I have no idea which change triggers that "sdist" is now picking up `setup_requirements.py`

**Comment by dev-zero** [comment] 2017-10-17 13:50
Well, I can now reproduce it with all branches in a clean virtualenv, but not with my distro-installed setuptools which seems to exhibit different behaviour. Anyway, adding the files to `MANIFEST.in` makes them to be present in all cases, see PR #780

**Comment by sphuber** [comment] 2017-10-18 12:43
The fix of the `MANIFEST.in` was merged in the `release_v0.10.0` branch which should fix the issue, so this issue can be closed, right?

**Comment by dev-zero** [comment] 2017-10-18 12:49
Yes. My tests indicate that after the change `setup_requirements.py` gets properly registered in the eggs `SOURCES.txt` and from there is included in the tarball generated by `python setup.py sdist`.

**Comment by dev-zero** [comment] 2017-10-18 12:50
... but I would merge it to develop (and release_0.11.0?) as well, before closing ;-)

**Comment by DropD** [comment] 2017-10-18 16:19
It should be noted that closing this issue does not mean that AiiDA is python 3 compatible, only that pip3 install won't fail. Most of the code will not run under python 3.

**Comment by oschuett** [comment] 2017-10-18 16:30
In that case I would suggest to open a new issue for the Python 3 support.

I was really hopping that I could turn jupyter.materialscloud.org into a pure Python 3 project, while it's still young enough.

**Comment by dev-zero** [comment] 2017-10-18 16:48
@oschuett at the point it makes rather sense to have it as a python-2-3 project with a shared codebase, using six for example

See also issue #804 for some notes of Python 3 compatibility

**Comment by sphuber** [comment] 2017-10-20 13:44
The changes in the `MANIFEST.in` are up for merging in `develop` and `release_v0.11.0` through PR so I am closing this

**Closed by sphuber** 2017-10-20 13:44 UTC
