### ISSUE TITLE
 CalcJobNode.get_state() in none after submission of the job

### ISSUE THREAD

**Issue by marco-foscato** [aiidateam/aiida_core#2894] opened 2019-05-21 13:42 UTC
The get_state method in aiida/orm/nodes/process/calculation/calcjob.py is supposed to return the state of the calculation job, and it looks for attribute CALC_JOB_STATE_KEY 
The latter is CALC_JOB_STATE_KEY = 'state', but a CalcJobNode created from aiida.engine.submit has attribute 'process_state' and 'scheduler_state', but not 'state'.

**Comment by marco-foscato** [comment] 2019-05-21 13:48
sorry for typo.... "in none" --> "is none"

**Comment by ltalirz** [comment] 2019-05-21 13:51
@marco-foscato thanks for the report, I think that's something for @sphuber

**Comment by sphuber** [comment] 2019-05-21 17:15
This is most likely as intended. The most important attribute is the `process_state` as this is shared by all processes, not just `CalcJob`s. For `CalcJob`s there is an *additional* attribute `state` which gives some extra granularity, *while* the calculation job is active, because these states are basically at which transport task it is, which only makes sense while it is active

**Comment by ltalirz** [comment] 2019-05-21 17:37
>  For CalcJobs there is an additional attribute state which gives some extra granularity, while the calculation job is active, because these states are basically at which transport task it is, which only makes sense while it is active.

I would say in this case, if it is run on an inactive process, it should print a helpful message, such as 
>"get_state is supported only on active processes. You may want to use get_process_state" instead.

This issue also points out that having both `get_state` and `get_process_state` is confusing to new users.

**Comment by sphuber** [comment] 2019-05-21 17:47
I'd actually rather just remove it then if it is confusing, until an actual use case presents itself where this additional state is even needed in the first place.

**Comment by ltalirz** [comment] 2019-05-21 17:56
fine for me. @giovannipizzi ?

**Comment by marco-foscato** [comment] 2019-05-21 21:05
> This is most likely as intended. The most important attribute is the `process_state` as this is shared by all processes, not just `CalcJob`s. For `CalcJob`s there is an _additional_ attribute `state` which gives some extra granularity, _while_ the calculation job is active, because these states are basically at which transport task it is, which only makes sense while it is active.
> 
> So my guess is that you called `get_state` _after_ the calculation had finished. If this is not the case, it might be a bug, but otherwise it is as intended. We might need to update the documentation/tutorial where the `get_state` method is referenced.
> 
> Where did you find out about this method?

Note this was not an instruction in the tutorial (we are talking 4.4.3). I was just curious about the status of the calculation. So from within the Jupyter notebook page I used TAB to look into the attributes and methods of the object returned by 'submit(builder)'. 
I tried .st&lt;TAB&gt; guessing there was a 'state' value, found none, then I tried get_&lt;TAB&gt; and there I found 'get_state'. And yes, by then the calculation had finished.

**Comment by giovannipizzi** [comment] 2019-05-22 05:41
If you think it's confusing it's fine to remove it from the API, even if I think it's useful to be able to ask if the calculation is with the scheduler, being retrieved, ...
I don't think printing a message is a good idea being this a python API function.
One could maybe set the final state to something like "completed" if we want to be more clear (or, if we want to keep the current logic, document this in the `get_state` API). I remember that anyway we discussed this with @sphuber and decided to set the state to `None` (I think mainly because the state can be chosen from the `CalcJobState` enum in `aiida/common/datastructures`, and the idea would be to only keep "active" states in there. But I wouldn't be against adding another state that says "finished processing" without information if it had finished correctly or not, and leave this as the final state.

**Comment by sphuber** [comment] 2019-05-22 07:34
Thanks @marco-foscato for the explanation. I agree with @giovannipizzi , I do not think we should add a final state to it, that is what the process state is for. This is really something that is "additional" only for calculation jobs. I also think it might still be useful at some point, mostly for querying though, so the API method won't be that important. Things we can do to make its intention more clear is properly document it in the docstring and rename the method to something like `get_process_sub_state` or something to indicate that it is subordinate to the process state.

**Comment by ltalirz** [comment] 2019-05-31 20:55
@sphuber feel free to proceed with this

**Comment by zhubonan** [comment] 2019-05-31 21:01
I wonder if there is an equivalent thing to the old `FINISHED` or `FAILED` state as in the old `JobCalculation`. I just realized the exit code system here is really for critical errors (at least for `CalcJob`) and if I set it then nothing would be returned by the `parse_from_node` method of the `Parser`.

Of course, the other way to achieve the old behaviour is to set a state value in the returned `Dict` node at the plugin level. I did find the old way of getting a list of Calculation with their state either being `FINISHED` or `FAILED` rather useful for quickly finding which one I should pay attention to and inspect the issue.

**Comment by sphuber** [comment] 2019-05-31 21:40
The exit code is not necessarily for "critical" errors only. Whatever the code means, is up to the developer. The only rule from `aiida-core` is that a process state of `Finished` with exit status `0` equals "finished ok" and `Finished` with non-zero means "failed". You can still easily get a list of "failed" processes simply by doing `verdi process list -X`.

Regarding the `parse_from_node`, there you are right. What are you using it for? It operates as any other process function. Its "result" is whatever it returns. If it returns an `exit_code` than that is its result. I am using it for parser unit tests and realized that there I still want to be able to attach outputs, even when returning an `exit_code`. I made a fix for this that I will put in a PR soon.

**Comment by zhubonan** [comment] 2019-05-31 21:44
Ahh I see, I misunderstood that function is used for actual `CalcJobs`. Just to confirm, `CalcJob` with non-zero return code should still give the outputs nodes right?

**Comment by sphuber** [comment] 2019-05-31 21:46
yes, as long as you attach the nodes with `self.out` in the parser, then they should be part of the outputs. The `parse_from_node` is a nifty trick to "reparse" the outputs from a completed calculation job. It will automatically wrap it in a `calcfunction` such that the "act of reparsing" is also recorded in the provenance graph. The newly parsed outputs will be the outputs of the `CalcFunctionNode` that represents the parsing. Hope that makes sense.

**Comment by zhubonan** [comment] 2019-05-31 21:48
I see, thanks for the clarification.

**Comment by sphuber** [comment] 2019-05-31 21:55
> @sphuber feel free to proceed with this

Not really sure what he agreed upon solution is though. Are you saying that just stating clearly in the docstring what the purpose of `get_state` is enough to close this for you?

**Comment by sphuber** [comment] 2019-06-22 08:02
This is the final decision:
* Issue #2854 will take care of migration old invalid `state` attributes to corresponding `process_state` etc.
* The only remaining valid `state` attributes are then those in `aiida.common.datastructures.CalcJobState`
* I will update the `get_state` docstring to clarify the purpose and that it will only be set while the corresponding process is active
* The method `get_state` will return `None` if an invalid state is detected instead of excepting

**Closed** 2019-06-22 09:06 UTC
