### ISSUE TITLE
Problem during verdi setup (maybe connected to new control module?)

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#747] opened 2017-10-05 16:31 UTC
E. Bosoni reports the following error when doing verdi setup SiestaAiidaTest
```
verdi setup SiestaAiidaTest
Setting up profile SiestaAiidaTest.
AiiDA backend (available: django, sqlalchemy - sqlalchemy is in beta mode): django
Default user email: [xxx]@[xxx.yy]
Database engine (available: postgresql_psycopg2, mysql - mysql is deprecated): postgresql_psycopg2
PostgreSQL host: localhost
PostgreSQL port: 5432
AiiDA Database name: siestatestdb
AiiDA Database user: siestatest
AiiDA Database password: XXXXXX
AiiDA repository directory: /home/yyy/TestAiidaSiestapy/.aiida/repository-SiestaAiidaTest/
The repository /home/yyy/TestAiidaSiestapy/.aiida/repository-SiestaAiidaTest/ will be created.
Executing now a migrate command...
...for Django backend
Operations to perform:
  Apply all migrations: sessions, db, sites, kombu_transport_django, contenttypes, auth
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying db.0001_initial... OK
  Applying db.0002_db_state_change... OK
  Applying db.0003_add_link_type... OK
  Applying db.0004_add_daemon_and_uuid_indices... OK
  Applying db.0005_add_cmtime_indices... OK
  Applying kombu_transport_django.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
== Postgres found, installing transitive closure engine ==
Database was created successfully
Loading new environment...
Installing default AiiDA user...
Starting user configuration for xxx@xxxx.yy...
First Name: Xxx
Last Name: Yyy
Institution: Zzz
Traceback (most recent call last):
  File "/home/xxx/TestAiidaSiestapy/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/home/xxx/TestAiidaSiesta/aiida_core/aiida/cmdline/verdilib.py", line 1040, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/xxx/TestAiidaSiesta/aiida_core/aiida/cmdline/verdilib.py", line 1025, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/home/xx/TestAiidaSiesta/aiida_core/aiida/cmdline/verdilib.py", line 353, in run
    _setup_cmd.invoke(ctx)
  File "/home/xxx/TestAiidaSiestapy/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxx/TestAiidaSiestapy/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/xxx/TestAiidaSiesta/aiida_core/aiida/cmdline/verdilib.py", line 407, in _setup_cmd
    setup(**kwargs)
  File "/home/xxx/TestAiidaSiesta/aiida_core/aiida/cmdline/verdilib.py", line 590, in setup
    user.configure.main(args=[email])
  File "/home/xxx/TestAiidaSiestapy/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/xxx/TestAiidaSiestapy/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxx/TestAiidaSiestapy/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/xxx/TestAiidaSiesta/aiida_core/aiida/cmdline/commands/user.py", line 152, in configure
    do_configure(email, first_name, last_name, institution, no_password)
  File "/home/xxx/TestAiidaSiesta/aiida_core/aiida/cmdline/commands/user.py", line 62, in do_configure
    user, created = get_or_new_user(email)
TypeError: get_or_new_user() takes exactly 0 arguments (1 given)
```
Is this expected? Probably it happened after the new `aiida.control` module has been created?

BTW, the name of the function is strange, it should probably be `get_or_create_user`? or `new` is used instead of `create` (but it's not a verb...)?

**Comment by nmounet** [comment] 2017-10-10 07:51
This issue seems to have been introduced by commit 323a54c .

**Comment by nmounet** [comment] 2017-10-10 08:01
REQUIRED_FIELDS is defined only for the AbstractUser class, but not for its dependent class, the User class.

**Comment by DropD** [comment] 2017-10-10 09:37
`get_or_new_user` constructs a user (if it doesn't exist) but does not store it. `create` always has the semantics of storing.

**Comment by nmounet** [comment] 2017-10-10 09:38
Actually, there is just a conflict between the aiida.cmdline.commands.user.User class and the aiida.orm.implementation.<BACKEND>.user.User class.
Should be solved by putting back the import

from aiida.orm.implementation import User

in aiida/cmdline/commands/user.py, in "do_configure".

**Comment by nmounet** [comment] 2017-10-10 09:41
One might also want to write a test for this?

**Comment by DropD** [comment] 2017-10-10 09:44
The problem is that get_or_new_user has changed signature and now only takes keyword arguments, the call in do_configure has not yet been adjusted.

**Comment by DropD** [comment] 2017-10-18 12:50
duplicate of #764

**Closed by DropD** 2017-10-18 12:50 UTC
Labels: topic/VerdiCommandLine, type/bug, type/trivial
