### ISSUE TITLE
Usage description does not match expected format for export create

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida_core#1696] opened 2018-06-28 10:14 UTC
`(envaiida)$ verdi export create -c 1`
`Usage: verdi export create [OPTIONS] OUTFILE`
`Error: Missing argument "outfile".`

`(envaiida)$ verdi export create -c 1 testfile`
`Usage: verdi export create [OPTIONS] OUTFILE`
`Error: Invalid value for "-c" / "--computers": could not convert ('1', 'testfile') into type <type 'int'>`

**Comment by sphuber** [comment] 2018-06-28 14:46
This is a problem that you will encounter all over the command line. The `OUTFILE` is a positional argument and the `-c` is an option that can take multiple values. The problem is that the parser cannot figure out whether the `testfile` in this case corresponds to the `OUTFILE` argument, or whether it is another value for the `-c` flag. This is a common problem for CLI and not specific to AiiDA. To break the amibiguity, the endopts flag `--` exists. This indicates the end of options and so the parser knows that everything after that should be interpreted as an argument. So to fix your command, type:

```
verdi export create -c 1 -- testfile
```

We are currently working on the command line and this should be merged within a week or two and I will make sure to put this in the documentation. Additionally we can think if we can attempt to detect the problem and at the very least emit a suggestion/warning, or maybe even try to fix it, but I am not sure if this is feasable

**Comment by sphuber** [comment] 2018-07-23 13:06
This was fixed in #1777 that updated the documentation detailing this situation

**Closed by sphuber** 2018-07-23 13:06 UTC
Labels: priority/quality-of-life, topic/DocumentationAndCodeStructure, topic/VerdiCommandLine
