### ISSUE TITLE
`verdi` fails on python 3.7

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2088] opened 2018-10-23 08:24 UTC
```
$  verdi
Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/coding-week-2018-10/bin/verdi", line 5, in <module>
    from aiida.cmdline.commands.cmd_verdi import verdi
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/cmdline/commands/__init__.py", line 19, in <module>
    from aiida.cmdline.commands import (cmd_calculation, cmd_code, cmd_comment, cmd_completioncommand, cmd_computer,
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/cmdline/commands/cmd_calculation.py", line 374
    result = control_panel._communicator.await(future[1])
```

Solution for the moment: go back to python 3.6

**Comment by sphuber** [comment] 2018-10-23 10:40
Duplicate of #1994 , this will be fixed when the `new_engine` branch will be merged next week

**Closed** 2018-11-07 09:19 UTC
Labels: type/duplicate
