### ISSUE TITLE
Daemon crashing due to InvalidConnection error to the database

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida_core#308] opened 2017-01-10 10:05 UTC

**Comment by toxa81** [comment] 2017-01-10 10:55
Were you actually able to reproduce it? I'm now installing a fresh Linux virtual box to setup aiida from scratch and see how it works there.

**Comment by fernandogargiulo1986** [comment] 2017-01-10 11:06
Hi Anton,

we actually just reproduced it  kind of by chance, when testing the 
AiiDA tutorial with the new version of the code. The problem seems to be 
related to a concurrency of the threads issued by celery (task-queue 
manager used by the AiiDA daemon) when emitting database queries through 
the querybuilder.

Some of us are already working on fixing the issue.

Bests

Fernando

**Comment by toxa81** [comment] 2017-01-10 11:16
Great! I thought it was my local Python glitch!

Cheers,
Anton.

**Comment by szoupanos** [comment] 2017-01-13 10:20
This issue should not be closed before trying to add tests for this (or finding a clear reason why we can not add at this stage). #309 provides a fix but my understanding is that there were no tests.

**Comment by lekah** [comment] 2017-01-15 16:41
The test would need to reproduce the real life use case within the daemon. We could only reproduce the error within the daemon, the tasks by themselves (executed sequentially) work fine. There is also the problem that in one case the problem appeared only after running the period for a while, and in other cases it never occurred. I can't come up with an automatic test, and I don't think it's possible to create a test within the infrastructure at hand.

**Comment by lekah** [comment] 2017-01-15 16:43
@toxa81 Did #309 resolve your problem?

**Comment by toxa81** [comment] 2017-01-16 09:34
Yes, it works now as expected. Thanks for the quick fix!

**Comment by giovannipizzi** [comment] 2017-01-20 00:05
Since there is no easy way, currently, to test for this use case, I will close this issue (but with the new docker setup, we might be able to test complex cases like this)

**Closed by giovannipizzi** 2017-01-20 00:05 UTC
