### ISSUE TITLE
policy when job is not found by Scheduler (temporarily) 

### ISSUE THREAD

**Issue by zhubonan** [aiidateam/aiida_core#1505] opened 2018-05-09 11:06 UTC
I have notices recently that some of my jobs was considered as  `COMPUTED` by aiida while it was in fact still running on the cluster. Looking at the `execmanager.py` code I found that by default when a job is not found the daemon will assume it was finished and start to retrieve. I noticed it mostly happened at midnight - it may due to the cluster's scheduler's maintenance cycle etc, but some jobs running at the same time survived and was still at `WITHSCHEDULER` state the next day. 

I did not turn on debug logging level but still the `_last_jobinfo()` of the falsely retrieved calculation gives a dict with `job_state` still in  `RUNNING`. So it is likely that the job is not returned by `Scheduler.getJobs` in `execmanager.update_running_calcs_status` function. I am using ARCHER which has a PBS scheduler. By the way, I wonder how I can check the scheduler's log for further information.

I can understand the default behavior is aimed at those jobs have finished a long time ago and not showing up any more in the scheduler. Nevertheless, I think it would be worth having a grace period.  Perhaps we can add a transient "UNKOWN" state and/or give a maximum time before considering it to be `COMPUTED` and start retrieving. It maybe also worth adding a time stamp for the JobInfo dictionary generated to track how long a job has being missing since last seen.

My aiida version is 0.11.4 but I just briefly checked the develop branch and it seems this default behavior is the same with the new daemon.

**Comment by zhubonan** [comment] 2018-05-14 08:50
Thanks for comment and info from @broeder-j . I think my problem here is not with the planned maintenance but just some jobs are temporarily missing when queried. Then AiiDA daemon thinks the job is finished immediately and starts to retrieve. Hence we have a false positive - and such error is not obvious to spot as the parsed results just looks like the a job ran out of walltime. It is also difficult and (dangerous) to reverse - I have to unlink output nodes and operate directly on the database to rewind the state of calculation.

**Comment by giovannipizzi** [comment] 2018-05-16 20:45
For the debug level, if you are using 0.12.0 or an earlier version, check this 
http://aiida-core.readthedocs.io/en/v0.11.4/troubleshooting/index.html?highlight=debug%20level#increasing-the-debug-level

For the specific issue: unfortunately in most schedulers the default policy is that the job disappears as soon as it finishes. I've never seen a scheduler with a job temporarily disappearing... Which variant/version of PBS are you using? Is this expected from the PBS docs? (My understanding is that it isn't...) Could you contact the sysadmins to check if this is a problem on their side?

The problem is that implementing a grace period (that probably should be per-computer, to avoid to have to wait on other computers where this is not needed) probably needs to implement a proper logic for a timeout. If you can confirm that this is an expected feature of PBS and not a bug in the implementation in the machine, we can try to assess more how much work it requires to implement what you ask.

**Comment by zhubonan** [comment] 2018-05-16 22:03
@giovannipizzi Thanks. I will turn on the debug logging while running calculations on that cluster and hopefully when it happens again I will see the message to confirm it was due to missing job. 
The version of PBS is PBSPro_12.2.401.141761. I don't think this is expected but it does not happen very often anyway. Like you said it it is probably a bug in the implement of the machine.

**Comment by giovannipizzi** [comment] 2018-05-23 12:04
Ok, thanks. I will close this for now, feel free to reopen if you find a way to reproduce the problem!

**Closed by giovannipizzi** 2018-05-23 12:04 UTC
Labels: requires discussion, topic/Daemon, topic/Schedulers, type/feature request
