### ISSUE TITLE
Verdi graph of workflows

### ISSUE THREAD

**Issue by cepellotti** [aiidateam/aiida_core#303] opened 2016-12-24 01:03 UTC
There is currently the possibility to show a graph containing all the children nodes of a root node.
It would be very useful to expand this functionality to show the full graph of all the nodes created within the same workflow (or sub workflow).

**Comment by giovannipizzi** [comment] 2017-01-20 00:02
I'm marking this as a duplicate of #286 and moving discussion there

**Closed by giovannipizzi** 2017-01-20 00:02 UTC
