### ISSUE TITLE
Celery worker hangs on broken pipe

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1006] opened 2017-12-18 16:20 UTC
The celery worker sometimes hangs during ticking a workflow. This can be fixed manually with 

``sudo tail -f /proc/<pid>/fd/2``

which just accesses the error pipe for the process. The pipe seems to be broken to begin with, so it's not clear to me what using ``tail`` accomplishes.

May be connected to: https://stackoverflow.com/questions/38840663/celery-worker-connection-with-rabbitmq-met-broken-pipe-error-in-gevent-or-eventl

The original issue where I encountered this is really involved, as a result of a long-running workchain with many sub-workchains. I'm currently trying to reproduce it with a simpler workchain.

**Comment by broeder-j** [comment] 2018-01-09 09:26
could this be related to #1032

**Comment by giovannipizzi** [comment] 2018-01-09 13:07
I think the reason of the behavior might be that AiiDA writes to the file descriptor, and when the buffer is full, it waits for it to be emptied. using `tail` will read and so empty it, and AiiDA will proceed.

@sphuber is working on fixing the logging behavior in #1030 , probably this will also fix this problem?

**Comment by greschd** [comment] 2018-01-09 13:11
Yeah, maybe #1030 can fix this.. Let me know when that's done, so I'll give it a try on my failing example. Unfortunately I didn't manage to get an easily reproducible version of the bug which we could integrate into the tests.

**Comment by giovannipizzi** [comment] 2018-01-10 15:28
Should be fixed by #1030, please reopen if this is not the case

**Closed by giovannipizzi** 2018-01-10 15:28 UTC
Labels: topic/Daemon, type/bug

**Comment by broeder-j** [comment] 2018-01-12 08:46
BTW. It was the cause for the daemon to be unkillable. Thanks!

**Comment by greschd** [comment] 2018-01-15 16:09
Sweet, it does seem to be fixed now. Thanks!
