### ISSUE TITLE
Daemon starts parsing before finishing retrieval

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#1748] opened 2018-07-13 14:28 UTC
We have a Quantum Espresso pw.x JobCalculation (our ref: 16177, d999848d-9291-4625-affc-59d1526d033a) that, after some time while retrieving, jobs goes into state FINISHED 400 (job state: FAILED).

After some debugging with higher log verbosity, what happens is the following:
- it starts retrieving at 03:34:12 PM
- the logic of parsing is called at 03:36:29PM, it does not find some files in the `retrieved_temporary_list` and it fails.
- however, looking at the logs, it keeps downloading files (within `retrieve_all`, with many small xml) for many more minutes. The last retrieval is at 03:39:49 PM.

The fact that the download is so small is not an issue of AiiDA (we investigated, it's slow because the network file system is very slow on the supercomputer in retrieving a lot of small files).

However, the real issue for AiiDA is: why it decides that it is should proceed with parsing before letting the retrieving function finish?

Is there e.g. a timeout that establishes how long (max) the retrieval can be?
In general, beside the specific case of a slow supercomputer, this is an issue (e.g. when retrieving big trajectory files, or similar).

**Comment by giovannipizzi** [comment] 2018-07-13 14:37
A cleaned-up log file that might help.

```
07/13/2018 03:34:12 PM <137527> aiida.work.transports: [DEBUG] Passing transport to <bound method RetrieveJob._execute of <aiida.work.job_processes.RetrieveJob object at 0x7f0e565082d0>>..
07/13/2018 03:34:12 PM <137527> aiida.aiida_quantumespresso.calculations.pw.PwCalculation: [INFO] Retrieving completed calculation<16177>
07/13/2018 03:34:12 PM <137527> aiida.execmanager: [DEBUG] Retrieving calc 16177
07/13/2018 03:34:12 PM <137527> aiida.execmanager: [DEBUG] [retrieval of calc 16177] chdir /scratch/snx3000/pizzi/aiida_run/d9/99/848d-9291-4625-affc-59d1526d033a
07/13/2018 03:36:22 PM <137706> aiida.aiida_quantumespresso.calculations.pw.PwCalculation: [INFO] Loaded process<16177> from saved state
07/13/2018 03:36:22 PM <137706> aiida.aiida_quantumespresso.calculations.pw.PwCalculation: [INFO] Waiting for calculation<16177> on retrieve
07/13/2018 03:36:22 PM <137706> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method RetrieveJob._execute of <aiida.work.job_processes.RetrieveJob object at 0x7f07588f2f90>>'
07/13/2018 03:36:28 PM <137706> aiida.work.transports: [DEBUG] Passing transport to <bound method RetrieveJob._execute of <aiida.work.job_processes.RetrieveJob object at 0x7f07588f2f90>>..
07/13/2018 03:36:28 PM <137706> aiida.aiida_quantumespresso.calculations.pw.PwCalculation: [INFO] Retrieving completed calculation<16177>
07/13/2018 03:36:28 PM <137706> aiida.execmanager: [DEBUG] Attempting to retrieve more than once calculation 16177: skipping!
07/13/2018 03:36:28 PM <137706> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:36:29 PM <137706> aiida.work.persistence: [INFO] Persisting process<16177>
07/13/2018 03:36:29 PM <137706> aiida.execmanager: [DEBUG] [parsing of calc 16177] Content of the retrieved_temporary_folder: 

07/13/2018 03:36:29 PM <137706> aiida.parser.PwParser: [ERROR] No retrieved folder found
07/13/2018 03:36:29 PM <137706> aiida.execmanager: [ERROR] [parsing of calc 16177] The parser returned an error, but it should have created an output node with some partial results and warnings. Check there for more information on the problem
07/13/2018 03:36:29 PM <137526> aiida.work.persistence: [INFO] Persisting process<16174>
07/13/2018 03:36:29 PM <137526> aiida.orm.implementation.general.calculation.work.WorkCalculation: [REPORT] [16174|PwBaseWorkChain|_handle_unexpected_failure]: Node 16177 does not have an output with link output_parameters
07/13/2018 03:36:29 PM <137526> aiida.orm.implementation.general.calculation.work.WorkCalculation: [REPORT] [16174|PwBaseWorkChain|_handle_unexpected_failure]: failure of PwCalculation<16177> could not be handled, restarting once more
07/13/2018 03:36:29 PM <137526> aiida.work.persistence: [INFO] Persisting process<16174>
07/13/2018 03:36:29 PM <137526> aiida.work.persistence: [INFO] Persisting process<16174>
07/13/2018 03:36:29 PM <137526> aiida.work.persistence: [INFO] Persisting process<16174>
07/13/2018 03:36:30 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method SubmitJob._execute of <aiida.work.job_processes.SubmitJob object at 0x7fbff3c20e90>>'
07/13/2018 03:36:36 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method SubmitJob._execute of <aiida.work.job_processes.SubmitJob object at 0x7fbff3c20e90>>..
07/13/2018 03:36:36 PM <137528> aiida.scheduler.slurm: [DEBUG] _get_run_line output: ["'srun' '/apps/daint/UES/jenkins/6.0.UP04/mc/easybuild/software/QuantumESPRESSO/6.1.0-CrayIntel-17.08/bin/pw.x' '-in' 'aiida.in'  > 'aiida.out' "]
07/13/2018 03:36:36 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/users/pizzi' && whoami
07/13/2018 03:36:38 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc11' './out/'
07/13/2018 03:36:39 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.save' './out/'
07/13/2018 03:36:49 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc6' './out/'
07/13/2018 03:36:50 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc4' './out/'
07/13/2018 03:36:50 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc3' './out/'
07/13/2018 03:36:51 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc18' './out/'
07/13/2018 03:36:52 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc15' './out/'
07/13/2018 03:36:53 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc12' './out/'
07/13/2018 03:36:55 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc17' './out/'
07/13/2018 03:36:56 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc10' './out/'
07/13/2018 03:36:57 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc5' './out/'
07/13/2018 03:36:58 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc1' './out/'
07/13/2018 03:36:59 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc13' './out/'
07/13/2018 03:37:00 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc2' './out/'
07/13/2018 03:37:02 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc9' './out/'
07/13/2018 03:37:03 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc16' './out/'
07/13/2018 03:37:06 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc7' './out/'
07/13/2018 03:37:06 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc8' './out/'
07/13/2018 03:37:08 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && cp -r -f '/scratch/snx3000/pizzi/aiida_run/4a/76/d73b-e40a-4bd3-87c8-466dca2e2dac/./out/aiida.wfc14' './out/'
07/13/2018 03:37:09 PM <137528> aiida.scheduler.slurm: [INFO] submitting with: sbatch '_aiidasubmit.sh'
07/13/2018 03:37:09 PM <137528> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/scratch/snx3000/pizzi/aiida_run/59/3b/67d6-45fb-4478-ba13-0e7ba3d764cc' && sbatch '_aiidasubmit.sh'
07/13/2018 03:37:11 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:37:11 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3b70950>>'
07/13/2018 03:37:17 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3b70950>>..
07/13/2018 03:37:18 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:37:18 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fc05e6e8b50>>'
07/13/2018 03:37:25 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fc05e6e8b50>>..
07/13/2018 03:37:25 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:37:25 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3f0a250>>'
07/13/2018 03:37:32 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3f0a250>>..
07/13/2018 03:37:33 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:37:33 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3ee1e50>>'
07/13/2018 03:37:39 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3ee1e50>>..
07/13/2018 03:37:40 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:37:40 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3ecf990>>'
07/13/2018 03:37:47 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3ecf990>>..
07/13/2018 03:37:47 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:37:47 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3f0a250>>'
07/13/2018 03:37:54 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3f0a250>>..
07/13/2018 03:37:58 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:37:59 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3ee1e50>>'
07/13/2018 03:38:05 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3ee1e50>>..
07/13/2018 03:38:06 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:38:06 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3b70950>>'
07/13/2018 03:38:12 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3b70950>>..
07/13/2018 03:38:13 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:38:13 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff5f6b210>>'
07/13/2018 03:38:19 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff5f6b210>>..
07/13/2018 03:38:20 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:38:20 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fc058d42890>>'
07/13/2018 03:38:27 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fc058d42890>>..
07/13/2018 03:38:27 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:38:27 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fc058d1cc50>>'
07/13/2018 03:38:34 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fc058d1cc50>>..
07/13/2018 03:38:35 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:38:35 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff71eb390>>'
07/13/2018 03:38:46 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff71eb390>>..
07/13/2018 03:38:47 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:38:47 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fc05d49ded0>>'
07/13/2018 03:38:54 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fc05d49ded0>>..
07/13/2018 03:38:55 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:38:55 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3ee4750>>'
07/13/2018 03:39:01 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3ee4750>>..
07/13/2018 03:39:02 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:39:02 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3f03110>>'
07/13/2018 03:39:08 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3f03110>>..
07/13/2018 03:39:09 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:39:09 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff63e5710>>'
07/13/2018 03:39:15 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff63e5710>>..
07/13/2018 03:39:16 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:39:16 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3f0f7d0>>'
07/13/2018 03:39:23 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3f0f7d0>>..
07/13/2018 03:39:23 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:39:23 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fc05e6e8b50>>'
07/13/2018 03:39:30 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fc05e6e8b50>>..
07/13/2018 03:39:30 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:39:31 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fc058d1cfd0>>'
07/13/2018 03:39:37 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fc058d1cfd0>>..
07/13/2018 03:39:38 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:39:38 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3ecf990>>'
07/13/2018 03:39:44 PM <137528> aiida.work.transports: [DEBUG] Passing transport to <bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fbff3ecf990>>..
07/13/2018 03:39:45 PM <137528> aiida.work.transports: [DEBUG] ...callback finished
07/13/2018 03:39:45 PM <137528> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method UpdateSchedulerState._execute of <aiida.work.job_processes.UpdateSchedulerState object at 0x7fc058c9cfd0>>'
07/13/2018 03:39:49 PM <137527> aiida.execmanager: [DEBUG] [retrieval of calc 16177] Retrieved temporary file or folder 'K00168'
07/13/2018 03:39:49 PM <137527> aiida.execmanager: [DEBUG] [retrieval of calc 16177] Retrieved temporary file or folder 'K00434'
07/13/2018 03:39:49 PM <137527> aiida.execmanager: [DEBUG] [retrieval of calc 16177] Retrieved temporary file or folder 'K00553'
07/13/2018 03:39:49 PM <137527> aiida.execmanager: [DEBUG] [retrieval of calc 16177] Retrieved temporary file or folder 'K00051'
07/13/2018 03:39:49 PM <137527> aiida.execmanager: [DEBUG] [retrieval of calc 16177] Retrieved temporary file or folder 'K00460'
...
```
here it continues but it's not relevant anymore.

The problem seems that after a couple of minutes, a new *retrieve* is launched (I copy again here the relevant lines from the log above):
```
07/13/2018 03:36:22 PM <137706> aiida.aiida_quantumespresso.calculations.pw.PwCalculation: [INFO] Loaded process<16177> from saved state
07/13/2018 03:36:22 PM <137706> aiida.aiida_quantumespresso.calculations.pw.PwCalculation: [INFO] Waiting for calculation<16177> on retrieve
07/13/2018 03:36:22 PM <137706> aiida.work.transports: [DEBUG] Got request for transport with callback '<bound method RetrieveJob._execute of <aiida.work.job_processes.RetrieveJob object at 0x7f07588f2f90>>'
07/13/2018 03:36:28 PM <137706> aiida.work.transports: [DEBUG] Passing transport to <bound method RetrieveJob._execute of <aiida.work.job_processes.RetrieveJob object at 0x7f07588f2f90>>..
07/13/2018 03:36:28 PM <137706> aiida.aiida_quantumespresso.calculations.pw.PwCalculation: [INFO] Retrieving completed calculation<16177>
07/13/2018 03:36:28 PM <137706> aiida.execmanager: [DEBUG] Attempting to retrieve more than once calculation 16177: skipping!
```
Probably since it cannot retrieve, it starts parsing.

So the question now becomes: why after a few minutes, the retrieval is called again.

**Comment by sphuber** [comment] 2018-07-16 16:36
This is another manifestation of the problem with the connection of the worker with RabbitMQ dropping. The following happens:

1. Worker A and B start and connect to RabbitMQ
2. Worker A picks up a task
3. Connection of Worker A is interrupted
4. Heartbeat of Worker A on RabbitMQ expires and RabbitMQ notices that the connection is lost
5. RabbitMQ assumes Worker A is dead and resends the task, to Worker B
6. Worker B starts to run the same task that Worker A is still running

The solution is not trivial. I am not sure if we can configure RabbitMQ's behavior to not resend the task when the connection is lost, but only send the message once. However, this would interfere with the mechanism that we use to automatically restart task when the daemon is restarted. We would have to start handling that manually.

The other option is some kind of locking mechanism. Accept that a task might be handed out to multiple workers, so before it is accepted by the worker it checks whether it is locked, and if that is the case is rejects the task. Otherwise, it will lock it and start working on it. However, this requires diligently unlocking the process when returning an uncompleted task and accepting that some tasks may be locked and then lost.

**Comment by sphuber** [comment] 2018-07-30 14:39
Manifestation and therewith duplicate of #1823

**Closed** 2018-11-07 09:19 UTC
Labels: priority/critical-blocking, topic/Daemon, topic/Workflows, type/bug, type/duplicate
