### ISSUE TITLE
verdi quicksetup does not make profile default

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2261] opened 2018-12-03 13:36 UTC
* set up new profile using `verdi quicksetup aiidaprofile`
 * `verdi profile list`
  `Critical: no default profile configured yet, run verdi setup`

Todo:
- [ ] list profiles, even if there is no default set
- [ ] if no default is detected using `verdi quicksetup`, make the new profile the default

**Comment by giovannipizzi** [comment] 2018-12-06 23:08
For `verdi profile list`, we leave for now a Critical message if no profile has been setup yet

**Comment by zhubonan** [comment] 2018-12-06 23:09
Almost done I will raise a pull request soon.


On 7 December 2018 00:08:10 Giovanni Pizzi <notifications@github.com> wrote:

For verdi profile list, we leave for now a Critical message if no profile has been setup yet

**Comment by giovannipizzi** [comment] 2018-12-06 23:15
Ops... we also were working on this while fixing another problem... it's in my PR #2315

**Comment by zhubonan** [comment] 2018-12-06 23:33
Just check your commit commit, don't think there will be conflict.

The problem is the line:  
` echo.echo_critical('could not load the configuration file: {}'.format(exception))`  
 will just end the process as sys.exit is called by `echo_critical`, i think we should use `echo_warning` instead. In case there is a profile but just no default_profile is set.

**Comment by sphuber** [comment] 2018-12-07 10:15
Fixed in PR #2315

**Closed by sphuber** 2018-12-07 10:15 UTC
