### ISSUE TITLE
verdi export does not export all parents

### ISSUE THREAD

**Issue by fernandogargiulo1986** [aiidateam/aiida_core#492] opened 2017-03-29 08:11 UTC
This problem manifested when exporting a group of nodes. No ``-P`` option was given to exclude the parents.

```bash
verdi -p elastic_constants export -g export_group -- exportFINAL.aiida
```

When importing the compressed archive in another AiiDA instance we get the error:

```bash
verdi -p elastic_constants_nh import exportFINAL.aiida 
**** Importing file exportFINAL.aiida
READING DATA AND METADATA...
EXTRACTING NODE DATA...
Traceback (most recent call last):
  File "/home/gargiulo/aiida/github/aiida_core/aiida/cmdline/commands/importfile.py", line 86, in run
    import_data_dj(filename)
  File "/home/gargiulo/aiida/github/aiida_core/aiida/orm/importexport.py", line 392, in import_data_dj
    "\n".join('* {}'.format(uuid) for uuid in unknown_nodes))
ValueError: The import file refers to 33 nodes with unknown UUID, therefore it cannot be imported. Either first import the unknown nodes, or export also the parents when exporting. The unknown UUIDs are:
* a4510733-e53c-4ccb-bc92-d3a199c38e61
* 0f1fed5c-0656-4590-a802-659f41e112ec
* fcbf73a1-dc9e-448a-a698-f2c65ce0ebae
* 4e3ed362-c008-4017-977a-b3f098a68d72
* 012e85ec-700f-44b5-9df7-3e46a7e975ad
* 5e1084dd-bd13-4f4c-9711-14e0745cdec6
* 4a59969a-b279-4b42-bb8c-b1918140948e
* 8cae8f3e-f73d-4ae1-830a-63f3ec36615a
* d0bc634a-1de3-4a0e-b26d-27f39f01a0e9
* 3fad0d64-ff6f-408d-808a-535ff2475134
* d3fbceff-e1d0-47d7-8c17-b0a97c935e1e
* 4771bd0d-7fcf-40e5-9443-96e2c68c3358
* 5a88321f-a44a-4076-bdc9-18d8cf223d3d
* 3525a414-9c77-438e-b08c-5f3eec9084e0
* 161dcb4b-94e6-4d75-8a36-cb4f0600f800
* beb2ce9e-0eb9-4fed-9f55-60cc99ac80ee
* 84bb3c52-5825-4dac-87cd-56c3299c99aa
* abe1c89a-58bf-4d67-8bc9-67ac04063238
* 623c877b-9f56-4583-b993-488d82a6865a
* a4f5d774-8d3e-43b7-9d98-8ae6acfe5c22
* 55aa947a-20df-44d7-9479-18da860c1184
* 789cfdc7-e524-4fa1-a9d1-275a7ba2f18e
* 92b1ed72-b1f0-4d35-a077-4ab789672fc1
* 8de0ec48-602d-4ea6-89ed-a1dfbd166fb7
* 016ecdcb-7fb4-4788-b141-0cbad9e1ae96
* 9f843913-0d44-450b-8051-27280031f809
* e8f8043e-8962-49bf-803b-51a00fa6b458
* a0322c61-04c8-49b0-82c2-2c7747ecceba
* df56ef84-48e9-4af1-a946-6182bda5c715
* bc2c8719-c9a9-4faa-8de5-783208d84bf2
* 19e1877f-cbe0-4d2c-ad63-f7704228447f
* 15c8612b-f458-43a8-bd1d-b12be5b1f858
* 0fd24baf-6051-4710-a666-87b14ebdcb7d

```

By running ``verdi generate graph`` on one of these nodes  we checked that they are actually parents of the nodes contained in  ``export_group``, so they should have been exported.
It might help to know that the missing nodes themselves originate from a previous import unlike their direct children and descendants.

It seems like the logic used to determine the parents of a reference node is different in the import and export functions.

**Comment by szoupanos** [comment] 2017-03-29 09:34
Just a small comment since I had a quick discussion with Fernando:
All the nodes that are not exported come from a different user (previous import). So maybe the export query (that selects the nodes to be exported) is not the expected one - or we should enrich it with more options.

**Comment by giovannipizzi** [comment] 2017-03-29 10:06
Interesting. My comment: I think the queries in the export should ignore the user and export/import all nodes, regardless of who the user is.

**Comment by nmounet** [comment] 2017-03-29 14:50
I agree with Giovanni.

**Comment by szoupanos** [comment] 2017-03-30 18:53
At #495 there is a test that shows that nodes generated by different users are exported & imported correctly.

We should see more carefully what is the problem behind this issue.

**Comment by szoupanos** [comment] 2017-04-05 16:18
I investigated this issue (using the Django backend) and I did not find anything suspicious.
More specifically, I used an export file provided by Fernando that contained (also) the nodes that could not be exported correctly.

1) I imported this file using a clean database.
2) I exported a specific node (let's call it node_a) that caused problems to Fernando. The export procedure completed without any problems.
3) I imported the exported nodes (2) to a new database. The import procedure completed without any problems.

I also checked and all the ancestors of node_a are included to the file that was exported at step (2).
I checked and all the nodes that were mentioned at the import logs at (3) and were the same that were exported at (2)

Since I can not reproduce the problem, I will close the issue.
If you have further information, please open it again.

**Closed by szoupanos** 2017-04-05 16:18 UTC
Labels: topic/ProvenanceConceptsAndLinks, topic/Sharing, type/bug, type/important
