### ISSUE TITLE
verdi quicksetup broken on Ubuntu?

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [aiidateam/aiida_core#964] opened 2017-11-29 14:53 UTC
Hello, 

I am new with aiida, I am trying to follow the  Quick installation steps.
I reach the point were I am doing the verdi quicksetup
when i reach the institution field, I write EPFL 
and then I get this 
Detected no known postgres setup, some information is needed to create the aiida database and grant aiida access to it.
If you feel unsure about the following parameters, first check if postgresql is installed. ( I installed )
If postgresql is not installed please exit and install it, then run verdi quicksetup again.
If postgresql is installed, please ask your system manager to provide you with the following parameters:

Do you know what can I do?

best, 

Andres Ortega

**Comment by ltalirz** [comment] 2017-11-29 15:02
I can confirm this issue on Ubuntu 16.04.3 with aiida 0.10.0

The setup via `verdi setup` works, see 
https://github.com/marvel-nccr/quantum-mobile/blob/be99f4e4d304f3de12918448defd52dfcabd0234/roles/aiida/tasks/aiida-core.yml#L84

But then when using `verdi quicksetup`, this is what I get
````
(aiida) max@qmobile:~$ verdi quicksetup
Profile name [quicksetup]: test
Email Address (identifies your data when sharing): leopold.talirz@epfl.ch
First Name: Leopold
Last Name: Talirz
Institution: EPFL
Detected no known postgres setup, some information is needed to create the aiida database and grant aiida access to it.
If you feel unsure about the following parameters, first check if postgresql is installed.
If postgresql is not installed please exit and install it, then run verdi quicksetup again.
If postgresql is installed, please ask your system manager to provide you with the following parameters:
postgres host [localhost]: 
postgres port [5432]: 
template [template1]: 
postgres super user [postgres]: 

trying to access postgres..
postgres password of postgres []: 
````

If anyone needs access to a Ubuntu system with this problem, just download the [Quantum Mobile VM](https://github.com/marvel-nccr/quantum-mobile/releases/tag/17.11.0)

**Comment by ltalirz** [comment] 2017-11-29 15:35
@DropD I believe the problem is in
https://github.com/aiidateam/aiida_core/blob/260e4ac95a280e58dbd06855e736958e9bd55ad7/aiida/control/postgres.py#L102-L105

In my setup, I have
````
> /home/max/.virtualenvs/aiida/local/lib/python2.7/site-packages/aiida/control/postgres.py(103)determine_setup()
-> if not self.pg_execute:
(Pdb) self.pg_execute
<function _pg_execute_not_connected at 0x2ad49696faa0>
(Pdb) (not self.pg_execute)
False
````
so, it doesn't enter into the Debian case although it should.

Replacing the condition by
`if self.pg_execute == _pg_execute_not_connected:`
solves the problem.

I believe this highlights two issues:
* the current code with checking whether self.pg_execute contains another function is not so easy to read. Can one make it a bit simpler?
* this needs to be tested

**Comment by szoupanos** [comment] 2017-11-30 00:08
@ltalirz @DropD 
Yes, lets have a look at it. This seems to be important enough
Travis uses, for the per-commit testing, the traditional approach (i.e. manual database creation and verdi setup - .travis-data/setup_profiles.sh).

There seem to be tests for quicksetup but may not cover all the cases (.travis-data/test_setup.py) and we should see why.

**Comment by DropD** [comment] 2017-11-30 10:09
The tests are run with Travis' default distribution. At the moment this is 14.04. There is currently no way we can use Travis to test on Ubuntu 16 without creating our own docker image to run the tests in.

@ltalirz Do not confuse the OS level `postgres` user with the Postgresql user `aiida_qs_max` (in your case). `postgres` is used to open the connection, whereas the Postgresql user is used to create the database for AiiDA and AiiDA will use it to manipulate the db. If `postgres` was used for this, AiiDA would have to be run as the `postgres` user.

It is obvious that this would work on MacOsX, since by default Posgresql there is installed to be accessible for the user installing it.

As for the password authentication error observed: Please try again, giving quicksetup the `--db-user <new_db_user_name>` option. It seems that the password AiiDA stored for your `aiida_qs_max` Postgresql user got changed in the meantime.

**Comment by ltalirz** [comment] 2017-11-30 10:51
@DropD You are right, I thought this might be unrelated.
When I provide the correct user and password (+ the fix of the if clause), I can now quicksetup on Ubuntu 16.04 again.

Perhaps there is a way to make it more clear which user is meant.

I also noticed that `verdi quicksetup` is missing a `--db-host` option, which is present in `verdi setup`.
On top of this, the options are named differently (`--db-user` vs `--db_user` etc.).
I can make an issue for this or let me know how you would prefer to handle this.

**Comment by DropD** [comment] 2017-11-30 11:04
@ltalirz The faulty line you found is fixed in #967 (I made a separate issue for it, #966). Thanks!

On a fresh setup (also on 16.04) this password problem should not occur. It mostly happens when a profile gets partially created. In that case it is also possible to delete the partial profile and quicksetup again.

The missing `db-host` option should have an issue, if none exists yet.

As far as I am concerned, the most widely used convention for cli options is to separate words with '`-`' (it is easiest to type). The reason why the older `setup` command does not use it is backwards compatibility. I have always felt that this should be unified as the commandline is being modernized. If it is ok with @giovannipizzi we can do that already.

**Comment by giovannipizzi** [comment] 2017-12-01 11:03
fine for me to rename db_user with db-user on the command line, please go ahead (but we should provide some deprecation time for the old options, as external pieces (might) depend on it, like some docker files etc.).

**Comment by ltalirz** [comment] 2017-12-12 13:09
Closing, this is fixed in develop and in release_v0.10.1

**Closed by ltalirz** 2017-12-12 13:09 UTC
Labels: type/bug, type/important
