### ISSUE TITLE
mtime not updated

### ISSUE THREAD

**Issue by mottetm** [aiidateam/aiida_core#2856] opened 2019-05-10 07:15 UTC
I'm still in v1.0.0a4 so not sure if this has been fixed already, but the `mtime` of WorkCalculation nodes does not update when the node is updated (step or completion of the WorkChain).

PS: I use SQLAlchemy as backend.

**Comment by sphuber** [comment] 2019-05-27 12:04
The current implementation of the `mtime` only pertains to the fields of the `Node` class. That is to say, the update of `mtime` is only triggered if one of the columns of the `Node` database model is updated. In SqlAlchemy, changing the attributes, which is a column, *should* update the mtime. However, adding links *should not*. What events are you observing that should trigger the mtime that are not happening? If it is the process state, for example, which is an attribute, that should indeed trigger the mtime. Do you have a minimal working example perhaps? On my production environment with SQLA, I do see the update in mtime being triggered

**Comment by sphuber** [comment] 2019-05-27 12:10
I actually just verified by accident that this functionality is working for Django by accident. The `ModelWrapper` which automatically triggers a save on the database row when a model field is updated on a stored node, only updates those specific fields. This circumvents that `auto_now` property of the `mtime` column. This bug is currently hidden, because the wrapper also invokes an update of the node version, which uses the `save` for the entire row. It is this subsequent call that then updates the `mtime`. However, once we remove the node version, which is in the works, this bug will surface. For SqlAlchemy however, this seems to be working properly, so as of yet, I have not been able to reproduce the reported bug.

**Comment by sphuber** [comment] 2019-06-27 14:59
I am failing to reproduce this on the current `develop` branch.
```
In [1]: data = Data().store()

In [5]: print(data.mtime)
2019-06-26 18:50:13.669573+02:00

In [6]: data.set_extra('test', 1)

In [7]: print(data.mtime)
2019-06-26 18:50:25.126955+02:00
```
To make sure that there is no difference for updatable attributes, since you described problems with `WorkChainNodes`, I also tested that, but still the `mtime` seems to be updating properly:
```
In [12]: from aiida.engine.processes import ProcessState

In [15]: node = WorkChainNode().store()

In [16]: print(node.mtime)
2019-06-26 18:53:05.657541+02:00

In [17]: node.set_process_state(ProcessState.FINISHED)

In [18]: print(node.mtime)
2019-06-26 18:53:15.148243+02:00
```
I think whatever the problem might have been has now been fixed.
I will close this for now. If  you manage to reproduce this on `develop`, feel free to reopen it.

**Closed by sphuber** 2019-06-27 14:59 UTC
Labels: aiida-core 1.x, priority/important, type/bug
