### ISSUE TITLE
import-export fails in a nested workchain environment

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida_core#754] opened 2017-10-11 10:54 UTC
If I export the output of a workchain 1, and workchain 1 also called another workchain, I get an error if export and import that data produced (created) by that workchain 1.

**Comment by sphuber** [comment] 2017-10-11 12:41
Looking at the the failing test, it seems that the problem is that the input link from the `input_2` node to the `slave` `WorkCalculation` is included in the export file, but the actual node `input_2` itself is not. For some reason the `export` function thus does not include all input nodes for each `Calculation` node it includes.

**Comment by sphuber** [comment] 2017-10-11 13:08
Ok the problem is the following. In the test you create a `WorkCalculation` called `master` which takes input `i1`, which calls a `WorkCalculation` called `slave` with an input `i2` and finally `master` produces output `o1`. Or schematically:

```
 ____       ___        ___       ____
|    | INP |   | CALL |   | INP |    |
| i1 | --> | m | -->  | s | <-- | i2 |
|____|     |___|      |___|     |____|
             |
             v  OUT
            ____
           |    |
           | o1 |
           |____|
```

The export call is now made on `o1`. Looking at the logic of the `export` function, all parent nodes are selected first, which will be `[i1, m]`. Of those, the first descendant (output) will be taken. Now here is the problem. Since the current export functionality is based on old link design, it does not consider link types as it assumes everything is either input or output link. The `slave` node connected by the `CALL` link therefore **looks** like an output node and gets added. So the final list of nodes is `[o1, m, i1, s]`. On this set the links are gathered, which again does not discriminate and so it takes everything. **Which means also the input link from `i2` to `s`**. But the node `i2` was never included, which is why the import breaks. Under the old link model, this assumption was fine, because given that output nodes could only ever have a single link, namely to their creator, this query was fine because their creator was guaranteed to already be in the set.

The direct problem therefore is that the "*get the first level of outputs of all parent nodes*" query also finds nodes connected by a `CALL` link, but their inputs nodes are not included. A quick and dirty fix would be to update the query to exclude `CALL` links, but I think a bigger problem is
found here. I think the `CALL` links should be followed but we should also include the corresponding input nodes.

**Comment by lekah** [comment] 2017-10-11 15:34
Was suspecting something like that. I'd go for the quick fix for now that gives us the same functionality as before (i.e. follow create links down and input links up). In the near future, we have to discuss how the export can be customized (and it should be customizable) to include/discard call / return links and whatever the user wants. For now we need to have at least the same functionality as with the old  system.

**Comment by sphuber** [comment] 2017-10-20 11:59
Merged into `release_v0.10.0` with PR #771

**Closed by sphuber** 2017-10-20 11:59 UTC
Labels: topic/Workflows, type/bug, type/important
